name: course_attendance_manager
description: Course Attendance Manager PRO
publish_to: "none"


version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.5.5
  file_picker: ^10.3.3
  excel: ^4.0.6
  pdf: ^3.11.3
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  web: ^1.1.1
  google_sign_in: ^7.2.0
  http: ^1.6.0
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

